FROM adoptopenjdk/openjdk11:latest

ARG DEBIAN_FRONTEND=noninteractive
ARG MAIN_DIR=tekton
ARG WORKPLACE_PATH=/opt/source

LABEL com.tekton.project.name="ProductsManagement" \
    com.tekton.project.key="productsmanagement" \
    com.tekton.project.version="1.0" \
    com.tekton.project.description="ProductManagement Application" \
    com.tekton.author.name="Christian Rivera" \
    com.tekton.author.email="crivera2093@gmail.com" \
    com.tekton.author.url="https://github.com/pSharpX"

WORKDIR ${WORKPLACE_PATH}/${MAIN_DIR}

COPY . .

# RUN THIS ONLY ON WINDOWS:
# The issue was that locally the mvnw script had Windows line endings (\r\n called CRLF).
# The solution was to convert the line endings to Linux EOL (\n called "LF")
RUN sed -i 's/\r$//' mvnw

RUN chmod +x mvnw && \
    ./mvnw clean package -DskipTests

# ENTRYPOINT ["java", "-agentlib:jdwp=transport=dt_socket,server=y,suspend=y,address=5005","-jar", "productsmanagement.jar"]
ENTRYPOINT ["./mvnw", "spring-boot:run"]