apiVersion: skaffold/v2beta26
kind: Config
metadata:
    name: products-management-dev-environment
deploy:
  kubectl:
    manifests:
      - ./k8s/database-cluster-ip-service.yaml
      - ./k8s/database-deployment.yaml
      - ./k8s/server-cluster-ip-service.yaml
      - ./k8s/server-deployment.yaml
build:
  local:
    push: false
  artifacts:
    - image: psharpx/productsmanagement-api
      context: .
      docker:
          dockerfile: Dockerfile.dev
          buildArgs:
            SPRING_PROFILES_ACTIVE: dev
      sync:
        manual:
          - src: "src/main/java/**/*.java"
            dest: .
          - src: "src/main/resources/**/*.properties"
            dest: .