apiVersion: v1
kind: Service
metadata:
  name: productsmanagement-server-service
spec:
  selector:
    app: productsmanagement
    component: server
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080