apiVersion: v1
kind: Service
metadata:
  name: ${project.artifactId}-database-service
spec:
  selector:
    app: ${project.artifactId}
    component: database
    version: ${project.version}
  type: ClusterIP
  ports:
    - port: 5432
      targetPort: 5432