apiVersion: v1
kind: Secret
metadata:
  annotations:
    jkube.io/git-url: https://github.com/pSharpX/productsmanagement.git
  labels:
    app: productsmanagement
    provider: jkube
    group: com.tekton
  name: ${project.artifactId}-secret
type: Opaque
data:
  password: eW91cl9kYXRhYmFzZV9wYXNzd29yZA==
stringData:
  DATABASE_USER: productsmanagement-user
  DATABASE_PASSWORD: productsmanagement-pass